-- -- CREATE TABLE book(
-- --     book_id INTEGER PRIMARY KEY,
-- --     title TEXT,
-- --     author TEXT,
-- --     price TEXT,
-- --     amount INTEGER
-- -- );
-- INSERT INTO book(book_id, title, author, price, amount)
-- VALUES (1, 'Мастер и Маргарита', 'Булгаков М.А.', 670.99, 3);